Repository wecode-bootcamp-korea/20-1st-HoxyLush-frontend, pull requests merged in 2021-05, with the labels that each got.

#3 [20기 권오재] Hoxy Lush? 5/13 종택님 리뷰 반영 완료 및 Nav바 수정
  public/images/eventbanner_1.jpg
  public/images/eventbanner_2.jpg
  public/images/eventbanner_3.png
  public/images/eventbanner_4.png
  public/images/mainImage_1.jpeg
  public/images/mainImage_2.jpeg
  public/images/mainImage_3.jpeg
  public/images/mainImage_4.jpeg
  public/images/mainImage_6.jpeg
  public/images/mainImage_7.jpeg
  public/images/mainImage_8.jpeg
  src/Routes.js
  src/components/Nav.js
  src/components/Nav.scss
  src/components/introduceLush.js
  src/components/productCategories.js
  src/config.js
  src/pages/Login/Login.js
  src/pages/Login/Login.scss
  src/pages/Login/Signup.js
  src/pages/Login/Signup.scss
  src/pages/Main/Main.js
  src/pages/Main/Main.scss
  src/pages/Main/mainasideproductdata.js
  src/pages/Main/mainproductdata.js
  src/styles/common.scss
Labels: Status: Conflict 발생, Status: 수정 요청

#2 [20기 김민정]Hoxy Lush? 장바구니 기능 구현 중
  public/data/cart.json
  public/data/category.json
  public/data/productList.json
  public/data/review.json
  public/index.html
  src/Routes.js
  src/components/ButtonsTest.js
  src/components/ButtonsTest.scss
  src/components/Modal.js
  src/components/Modal.scss
  src/components/OrderCountControler.js
  src/config.js
  src/pages/Login/Login.js
  src/pages/Main/Main.js
  src/pages/Order/Order.js
  src/pages/Order/Order.scss
  src/pages/Order/components/CartList.js
  src/pages/Order/components/CartList.scss
  src/pages/Order/components/Favorit.js
  src/pages/Order/components/Favorit.scss
  src/pages/Order/components/OrderHeader.js
  src/pages/Order/components/OrderHeader.scss
  src/pages/Order/components/ProductInCart.js
  src/pages/Products/Components/AddToCart.js
  src/pages/Products/Components/AddToCart.scss
  src/pages/Products/Components/Buttons.js
  src/pages/Products/Components/Buttons.scss
  src/pages/Products/Components/Card.js
  src/pages/Products/Components/Card.scss
  src/pages/Products/Components/Category.js
  src/pages/Products/Components/Category.scss
  src/pages/Products/Components/Detail.js
  src/pages/Products/Components/Detail.scss
  src/pages/Products/Components/DetailImages.js
  src/pages/Products/Components/DetailImages.scss
  src/pages/Products/Components/DetailInfo.js
  src/pages/Products/Components/DetailInfo.scss
  src/pages/Products/Components/DetailMiddle.js
  src/pages/Products/Components/DetailMiddle.scss
  src/pages/Products/Components/DetailReview.js
  src/pages/Products/Components/DetailReview.scss
  src/pages/Products/Components/Headers.js
  src/pages/Products/Components/Headers.scss
  src/pages/Products/Components/Lists.js
  src/pages/Products/Components/Lists.scss
  src/pages/Products/Components/OrderInfo.js
  src/pages/Products/Components/OrderInfo.scss
  src/pages/Products/Components/Review.js
  src/pages/Products/Detail.js
  src/pages/Products/Products.js
  src/pages/Products/Products.scss
  src/styles/variables.scss
Labels: Status: 도움 요청, Status: 수정 요청

#7 Modify : Login.js, ID, 비밀번호 입력창에 validation 추가
  src/pages/Login/Login.js
Labels: Status: 리뷰 요청

#9 [20기 김민정 ] button component 재사용으로 인한 변경
  src/components/Button.scss
  src/pages/Products/Products.js
  src/pages/Products/Products.scss
Labels: Status: 리뷰 요청

#8 [20기 김민정] Conflict released
  src/config.js
  src/pages/Products/Components/Card.js
  src/pages/Products/Components/Detail.js
  src/pages/Products/Components/DetailImages.js
  src/pages/Products/Components/DetailMiddle.js
  src/pages/Products/Components/OrderInfo.js
  src/utilityFunc.js
Labels: Status: 리뷰 요청

#11 [20기 권오재] 메인페이지 슬라이드 이미지 교체 및 레이아웃 수정
  src/pages/Login/Login.js
  src/pages/Login/Signup.js
  src/pages/Main/Main.js
  src/pages/Main/Main.scss
Labels: Status: 리뷰 요청

#12 [20기 김민정]Detail page - 장바구니 담기 서버 연결 완료
  .vscode/settings.json
  public/data/selectedProduct.json
  src/Routes.js
  src/components/Button.scss
  src/config.js
  src/dist/config.dev.js
  src/pages/Main/Main.js
  src/pages/Order/components/LikeProduct.js
  src/pages/Order/components/ProductInCart.js
  src/pages/Products/Components/AddToCart.js
  src/pages/Products/Components/Card.js
  src/pages/Products/Components/Detail.js
  src/pages/Products/Components/Detail.scss
  src/pages/Products/Components/DetailImages.js
  src/pages/Products/Components/DetailInfo.js
  src/pages/Products/Components/OrderInfo.js
  src/pages/Products/Products.js
  src/utilityFunc.js
Labels: Status: 리뷰 요청

#14 [20기 권오재] 로그인 화면 validation 추가
  src/pages/Login/Login.js
Labels: Status: 리뷰 요청

#13 [20기 김민정] Cart page - 서버 연결 완료
  src/Routes.js
  src/config.js
  src/pages/Order/Order.js
  src/pages/Order/components/CartList.js
  src/pages/Order/components/Like.js
  src/pages/Order/components/LikeProduct.js
  src/pages/Order/components/ProductInCart.js
  src/pages/Products/Products.js
  src/uitilityFunc.js
Labels: Status: 리뷰 요청

#15 [20기 김민정] products page - utility function 추가 및 페이지 연결
  src/components/Button.scss
  src/config.js
  src/pages/Main/Main.js
  src/pages/Products/Components/AddToCart.js
  src/pages/Products/Components/Card.js
  src/pages/Products/Components/Detail.js
  src/pages/Products/Components/Headers.scss
  src/pages/Products/Components/Lists.js
  src/pages/Products/Components/OrderInfo.js
  src/pages/Products/Components/OrderInfo.scss
  src/pages/Products/Products.scss
Labels: Status: 리뷰 요청

#16 [20기 권오재] Footer 구현
  public/images/footerImage.png
  src/Routes.js
  src/components/Footer.scss
  src/components/footer.js
  src/pages/Login/Login.js
  src/pages/Main/Main.js
Labels: Status: 리뷰 요청

#18 [20기 김민정 ] Merging
  src/pages/Products/Components/Detail.js
  src/pages/Products/Components/DetailInfo.js
Labels: Status: 리뷰 요청

#19 [20기 김민정] Merging
  src/Routes.js
  src/pages/Order/Order.js
  src/pages/Order/components/CartList.js
  src/pages/Order/components/Like.js
  src/uitilityFunc.js
Labels: Status: 리뷰 요청
